# Generated by Django 4.2.18 on 2025-02-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_request',
            old_name='nbre_hour',
            new_name='num_hour',
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
